title: Looping over dictionaries with Python
hero_image: images/banner.png
description: Looping over dictionaries with Python
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: cc-prototype
duration: 1
listed: false
ingredient: true
interests: ""
technologies: "python"
steps:
  - title: Looping over dictionaries with Python
