title: Looping over dictionaries with Python
hero_image: images/banner.png
description: Looping over dictionaries with Python
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: cc-prototype
duration: 1
listed: false
ingredient: true
interests: "jokes/pranks, sports, art/design, photography, games, outside/weather/nature, space, animals, music/sound"
technologies: "scratch, python, html/css, micro:bit"
steps:
  - title: Looping over dictionaries with Python
