---
title: Crear bucles para iterar sobre diccionarios con Python
hero_image: images/banner.png
description: Crear bucles para iterar sobre diccionarios con Python
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "python"
steps:
  - title: Crear bucles para iterar sobre diccionarios con Python
