---
title: Looping over dictionaries with Python
hero_image: images/banner.png
description: Looping over dictionaries with Python
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "python"
steps:
  - 
    title: Looping over dictionaries with Python
